name: Test warnings
on:
  push:
    branches:
      - action-annotations
  workflow_dispatch:

jobs:
  checks-action:
    runs-on: ubuntu-latest
    steps:
    - uses: LouisBrunner/checks-action@v1.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test success
        conclusion: success
    - uses: LouisBrunner/checks-action@v1.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test neutral
        conclusion: neutral
        output: |
          {"summary":"[Build Scan URL: https://ge.gradle.org](https://ge.gradle.org)", "text_description":"Here is a bunch of text\nAnother line\nLine *with* _markdown_"}
    - uses: LouisBrunner/checks-action@v1.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test with annotation
        conclusion: neutral
        output: |
          {"summary":"[Build Scan URL: https://ge.gradle.org](https://ge.gradle.org)", "text_description":"Here is a bunch of text\nAnother line\nLine *with* _markdown_"}
        annotations: |
          [{"path":".github/workflows/action-annotations.yml","start_line":"1","end_line":"2","annotation_level":"warning","title":"Custom annotation","message":"This is my custom annotation"}]


  checks-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create status check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_COMMIT: ${{ github.sha }}
        run: |
          curl \
          -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/bigdaz/test-gradle-command-action/check-runs \
          -d '{"name":"dummy check", "head_sha": "${{github.sha}}","status":"in_progress"}'
