name: Test warnings
on:
  push:
    branches:
      - action-annotations
  workflow_dispatch:

jobs:
  seed-build:
    runs-on: ubuntu-latest
    steps:
    - name: Echo warning
      run: echo "::warning title=DAZ,file=gradle-project/settings.gradle,line=3::Missing semicolon"

  
