name: output file contents
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  seed-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - name: read file contents directly
      run: cat README.md
    - name: read file contents to output
      id: read-file
      run: echo ::set-output name=contents::$(cat README.md)
    - name: Echo file contents to log
      run: echo ${{steps.read-file.outputs.contents}}

  
