name: CCUD test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout CCUD
        uses: actions/checkout@v2
        with:
          repository: gradle/gradle-enterprise-build-config-samples
          path: gradle-enterprise-build-config-samples
          ref: dd/github-actions-links
          
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: build
        uses: gradle/gradle-build-action@v2
        with: 
          arguments: build
          build-root-directory: gradle-project

