name: OrderedProperties

on:
  workflow_dispatch:

jobs:
  configuration-cache-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "etiennestuder/java-ordered-properties"
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "temurin"
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true
      - name: Seed config cache
        run: |
          ./gradlew --configuration-cache build 2>&1 | tee -a /tmp/gradle-build.log
      - name: Load config cache
        run: |
          ./gradlew --configuration-cache build 2>&1 | tee -a /tmp/gradle-build.log
      - name: Parse outputs
        run: |
          echo ::set-output name=configCacheStored::$(grep "Configuration cache entry stored" /tmp/gradle-build.log | wc -l)
          echo ::set-output name=configCacheReused::$(grep "Configuration cache entry reused" /tmp/gradle-build.log | wc -l)
      - name: Fail if configuration cache was not reused
        run: exit 1
        if: steps.gradle-build.outputs.configCacheStored != '1' || steps.gradle-build.outputs.configCacheReused != '1'
