#touch
name: dependency-graph
on:
  workflow_dispatch:

env:
  CACHE_DEBUG_ENABLED: true

jobs:
  seed-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup gradle
      uses: gradle/gradle-build-action@dd/dependency-graph
      with:
         build-root-directory: gradle-project
    - name: Upload dependency graph
      working-directory: gradle-project
      run: |
        curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/bigdaz/test-gradle-build-action/dependency-graph/snapshots -d @build/reports/github-dependency-report/github-dependency-manifest.json


