#touch
name: dependency-graph
on:
  workflow_dispatch:
  push:

env:
  CACHE_DEBUG_ENABLED: true

jobs:
  seed-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup gradle
      uses: gradle/gradle-build-action@dd/dependency-graph
      with:
         build-root-directory: gradle-project
    - name: Script upload
      uses: actions/github-script@v6
      with:
        script: |
          await github.request('POST /repos/bigdaz/test-gradle-build-action/dependency-graph/snapshots', {
            version: 0,
            sha: '${{ github.sha }}',
            ref: '${{ github.ref }}',
            job: {
              correlator: '${{ github.workflow }}',
              id: '${{ github.run_id }}'
            },
            detector: {
              name: 'octo-detector',
              version: '0.0.1',
              url: 'https://github.com/octo-org/octo-repo'
            },
            scanned: '2023-05-10T20:25:01Z',
            manifests: {
              'package-lock.json': {
                name: 'package-lock.json',
                file: {
                  source_location: 'src/package-lock.json'
                },
                resolved: {
                  '@actions/core': {
                    package_url: 'pkg:/npm/%40actions/core@1.1.9',
                    dependencies: [
                      '@actions/http-client'
                    ]
                  },
                  '@actions/http-client': {
                    package_url: 'pkg:/npm/%40actions/http-client@1.0.7',
                    dependencies: [
                      'tunnel'
                    ]
                  },
                  tunnel: {
                    package_url: 'pkg:/npm/tunnel@0.0.7'
                  }
                }
              }
            },
            headers: {
              'X-GitHub-Api-Version': '2022-11-28'
            }
          })          

#     - name: Upload dependency graph
#       run: |
#         curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/bigdaz/test-gradle-build-action/dependency-graph/snapshots -d @gradle-project/build/reports/github-dependency-report/github-dependency-manifest.json


