name: Experiment
on: 
  workflow_dispatch:

jobs:
  test-vars:
    runs-on: ubuntu-latest

    steps:
    - name: Dump github context
      run: echo '${{ toJSON(github) }}'
    - name: Dump vars context
      run: echo '${{ toJSON(vars) }}'
    - name: Dump env context
      run: echo '${{ toJSON(env) }}'
    - name: Print env on runner
      run: env
