name: Experiment
on: 
  workflow_dispatch:
  push:

jobs:
  job1:
    name: Debug
    runs-on: windows-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Run Gradle
      run: gradle tasks
      working-directory: gradle-project
    - name: Find find and touch
      if: ${{ always() }}
      run: |
        where.exe find
        where.exe touch
        where.exe ls
    - name: Run git find
      if: ${{ always() }}
      run: |
        C:\Program` Files\Git\usr\bin\find.exe C:\Users\runneradmin\.gradle
        C:\Program` Files\Git\usr\bin\find.exe C:\Users\runneradmin\.gradle -name *

        
