name: Experiment
on: 
  workflow_dispatch:
  push:

jobs:
  job1:
    name: Debug
    runs-on: windows-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
#     - name: List files
#       run: ls -la
    - name: Find find and touch
      run: |
        where.exe find.exe
        where.exe find
        where.exe touch
    - name: Run find
      if: ${{ always() }}
      run: find
    - name: Run git find
      if: ${{ always() }}
      run: C:\Program Files\Git\usr\bin\find.exe
