name: main
on:
  push:
  workflow_dispatch:
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - uses: gradle/gradle-build-action@releases/v2
      with:
        build-root-directory: gradle-project
        wrapper-directory: gradle-project
        arguments: build --build-cache
        
  read-only:
    needs: gradle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - uses: gradle/gradle-build-action@releases/v2
      with:
        build-root-directory: gradle-project
        wrapper-directory: gradle-project
        arguments: build --build-cache
        gradle-user-home-cache-enabled: read-only
        project-dot-gradle-cache-enabled: read-only


