# .github/workflows/gradle-build-pr.yml
name: Run Gradle on push
on: push
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - name: Print built-in Gradle version
      run: gradle --version
    - name: Print built-in Gradle path
      run: which gradle
    - uses: eskatos/gradle-command-action@dd/experiments
      with:
        gradle-version: 6.9
        build-root-directory: gradle-project
        arguments: help --debug
      id: gradle
    - uses: eskatos/gradle-command-action@dd/experiments
      with:
        gradle-version: 6.9
        build-root-directory: gradle-project
        arguments: help --debug
      id: gradle2
