name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CACHE_DEBUG_ENABLED: true

jobs:
  seed-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        build-root-directory: gradle-project
        cache-artifact-bundles: |
          [
            ["generated-gradle-jars", "caches/*/generated-gradle-jars/*.jar"],
            ["wrapper-zips", "wrapper/dists/*/*/*.zip"],
            ["dependency-jars", "caches/modules-*/files-*/**/*.jar"],
            ["instrumented-jars", "caches/jars-*/*/"]
          ]

        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
        arguments: |
          check
          --build-cache
