# .github/workflows/gradle-build-pr.yml
name: Run Gradle on push
on: push
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - uses: gradle/gradle-build-action@dd/v14
      with:
        build-root-directory: gradle-project
        arguments: help
        configuration-cache-enabled: true

