name: main
on:
  push:
  workflow_dispatch:
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - uses: gradle/gradle-build-action@e11cdbdcfcf8d7e9416203728f4b02b4d11ff349
      with:
        build-root-directory: gradle-project
        arguments: help
        cache-artifact-bundles: |
           [
             ["generated-gradle-jars", "caches/*/generated-gradle-jars/*.jar"]
           ]


