# Change to workflow..
name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

#Bump
env:
  CACHE_DEBUG_ENABLED: true

jobs:
  seed-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - uses: octokit/request-action@v2.x
      id: create_check_run
      with:
        route: POST /repos/${{github.repository}}/check-runs
        head_sha: ${{ github.sha }}
        name: "Test check run"
        output: | # The | is significant!
          title: Test check run title
          summary: A summary of the test check run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: run gradle
      uses: gradle/gradle-build-action@releases/v2
      with:
        build-root-directory: gradle-project
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
        arguments: |
          check
          --build-cache

    # Update check run to completed, successful status
    - uses: octokit/request-action@v2.x
      with:
        route: PATCH /repos/${{github.repository}}/check-runs/{check_run_id}
        check_run_id: ${{ fromJson(steps.create_check_run.outputs.data).id }}
        conclusion: "success"
        status: "completed"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}