name: main
on:
  push:
  workflow_dispatch:

env:
  CACHE_DEBUG_ENABLED: true

jobs:
  seed-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - uses: gradle/gradle-build-action@8b1f1a38171b6ec35c8c7d536edcde9debb5194a
      with:
        build-root-directory: gradle-project
        arguments: help
        cache-artifact-bundles: |
          [
            ["generated-gradle-jars", "caches/*/generated-gradle-jars/*.jar"],
            ["wrapper-zips", "wrapper/dists/*/*/*.zip"],
            ["dependency-jars", "caches/modules-*/files-*/**/*.jar"],
            ["instrumented-jars", "caches/jars-*/*"]
          ]

  restore-build:
    needs: seed-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - uses: gradle/gradle-build-action@8b1f1a38171b6ec35c8c7d536edcde9debb5194a
      with:
        build-root-directory: gradle-project
        arguments: help
        cache-artifact-bundles: '[]'
        cache-read-only: true


