# Change to workflow..
name: main
on:
  push:
    branches:
      - main
  workflow_dispatch:

#Bump
env:
  CACHE_DEBUG_ENABLED: true
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  seed-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - name: run gradle
      uses: gradle/gradle-build-action@dd/check-run-per-build
      with:
        build-root-directory: gradle-project
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
        arguments: |
          check
          --build-cache

  another-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - name: run gradle
      uses: gradle/gradle-build-action@dd/check-run-per-build
      with:
        build-root-directory: gradle-project
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
        arguments: |
          check
          --build-cache
    
