name: main
on:
  workflow_dispatch:
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - uses: gradle/gradle-build-action@dd/v2
      with:
        build-root-directory: gradle-project
        arguments: build --build-cache
        cache-debugging-enabled: true
        
  read-only:
    needs: gradle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - uses: gradle/gradle-build-action@dd/v2
      with:
        build-root-directory: gradle-project
        arguments: build --build-cache
        gradle-cache-enabled: read-only
        cache-debugging-enabled: true


