# Change to workflow.
name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CACHE_DEBUG_ENABLED: true

jobs:
  seed-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        build-root-directory: gradle-project
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
        arguments: check
