# Change to workflow.
name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

#Bump
env:
  CACHE_DEBUG_ENABLED: true

jobs:
  seed-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - uses: actions/github-script@v5
      with:
        script: |
            if (context.payload.pull_request && context.payload.pull_request.head.repo.fork) {
                core.setOutput('sys-prop-args', '-DagreePublicBuildScanTermOfService=yes -DcacheNode=us')
            } else {
                core.setOutput('sys-prop-args', '-DcacheNode=us')
            }
    - name: run gradle
      env:
        DUMMY_SECRET:  ${{ secrets.DUMMY_SECRET }}
      uses: gradle/gradle-build-action@releases/v2
      with:
        build-root-directory: gradle-project
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
        arguments: |
          check
          --build-cache
  non-fork-job:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Add a notice on main
        if: ${{ github.event }}
        run: echo "::notice ::Doing stuff on main repo"
      - name: Add a notice on fork
        if: ${{ !github.event }}
        run: echo "::notice ::Doing stuff on FORK"

