name: Java Toolchains
on:
  push:

env:
  CACHE_DEBUG_ENABLED: true

jobs:
  report-toolchains:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, windows-2022, windows-2019, windows-2016, macos-11, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: print JAVA env
      run: env | grep JAVA | sort
    - name: print ANDROID env
      run: env | grep ANDROID | sort
    - name: run gradle
      working-directory: gradle-project
      run: gradle javaToolchains
