name: jvmargs test
on:
  workflow_dispatch:

env:
  CACHE_DEBUG_ENABLED: true

jobs:
  seed-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Gradle build
      uses: gradle/gradle-build-action@v2
      with:
        build-root-directory: gradle-project
        arguments: |
          check
          -Dorg.gradle.parallel=true
