#touch
name: main
on:
  workflow_dispatch:

env:
  CACHE_DEBUG_ENABLED: true
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1

jobs:
  seed-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup gradle
      uses: gradle/gradle-build-action@dd/cache-read-timeout
    - name: Run build
      id: gradle
      working-directory: gradle-project
      run: ./gradlew assemble
