name: main
on:
  workflow_dispatch:

env:
  CACHE_DEBUG_ENABLED: true

jobs:
  seed-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Write initial summary
      run: echo '### Hello world!' >> $GITHUB_STEP_SUMMARY
    - name: Setup gradle
      uses: gradle/gradle-build-action@v2
    - name: Print current dir
      run: pwd
    - name: Run build
      id: gradle
      working-directory: gradle-project
      run: ./gradlew --build-cache check
    - name: Write summary
      run: echo '### ${{ steps.gradle.outputs.build-scan-url }}' >> $GITHUB_STEP_SUMMARY
      
    
