#touch!!!
name: main
on:
  workflow_dispatch:

env:
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
  GRADLE_BUILD_ACTION_CACHE_KEY_PREFIX: "11-"

jobs:
  seed-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup gradle
      uses: gradle/gradle-build-action@prerelease/v3
      with:
        cache-read-only: false
    - name: Run gradle wrapper build
      working-directory: gradle-project
      run: ./gradlew assemble --configuration-cache
    - name: Run gradle 8.4 build
      working-directory: gradle-project
      run: gradle assemble --configuration-cache
