#touch
name: main
on:
  workflow_dispatch:

env:
  CACHE_DEBUG_ENABLED: true

jobs:
  seed-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build
      working-directory: gradle-project
      run: ./gradlew assemble
    - name: Run build again
      working-directory: gradle-project
      run: ./gradlew assemble
