#touch
name: main
on:
  workflow_dispatch:
  push:

env:
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  gradle-86-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup gradle
      uses: gradle/gradle-build-action@prerelease/v3
      with:
        cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
    - name: Run gradle build
      working-directory: gradle-project
      run: ./gradlew assemble --configuration-cache

  gradle-85-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup gradle
      uses: gradle/gradle-build-action@prerelease/v3
      with:
        gradle-version: 8.5
        cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
    - name: Run gradle build
      working-directory: gradle-project
      run: gradle assemble --configuration-cache

  gradle-80-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup gradle
      uses: gradle/gradle-build-action@prerelease/v3
      with:
        gradle-version: 8.0.2
        cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
    - name: Run gradle build
      working-directory: gradle-project
      run: gradle assemble --configuration-cache
