#touch
name: main
on:
  workflow_dispatch:
  push:

env:
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
  GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

jobs:
  config-cache-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup gradle
      uses: gradle/gradle-build-action@prerelease/v3
      with:
        cache-encryption-passphrase: x
    - name: Run gradle build
      working-directory: gradle-project
      run: ./gradlew assemble --configuration-cache
