name: main
on:
  workflow_dispatch:

env:
  CACHE_DEBUG_ENABLED: true

jobs:
  seed-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build
      id: gradle
      working-directory: gradle-project
      run: ./gradlew --build-cache check
    - name: Write summary
      env:
        BUILD_SCAN_URL: ${{ steps.gradle.outputs.build-scan-url }}
        GRADLE_ENTERPRISE_ACCESS_KEY: e.grdev.net=${{secrets.GRADLE_ENTERPRISE_ACCESS_KEY}}

      run: echo '### Hello world! ${{ steps.gradle.outputs.build-scan-url }}' >> $GITHUB_STEP_SUMMARY
      
    
