# Change to workflow.
name: non-fork
on:
  push:
  pull_request:

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  non-fork-job:
    if: ${{!github.event.repository.fork}}
    runs-on: ubuntu-latest
    steps:
      - name: Add a notice on main
        run: echo "::notice ::Build running in main repo"

  post-non-fork-job:
    needs: [non-fork-job]
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - name: Add a notice on post-non-fork
        run: echo "::notice ::Finished doing stuff on main repo"

  fork-job:
    if: ${{github.event.repository.fork}}
    runs-on: ubuntu-latest
    steps:
      - name: Add a notice on fork
        run: echo "::notice ::Doing stuff on FORKED repo"

  post-fork-job:
    needs: [fork-job]
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - name: Add a notice on post-fork
        run: echo "::notice ::Finished doing stuff on FORKED repo"