# Change to workflow.
name: non-fork
on:
  push:
  pull_request:

jobs:
  non-fork-job:
    runs-on: ubuntu-latest
    steps:
      - name: Add a notice on main
        if: ${{ secrets.DUMMY_SECRET }}
        run: echo "::notice ::Build running in main repo"

  post-non-fork-job:
    needs: [non-fork-job]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Add a notice on post-non-fork
        if: ${{ secrets.DUMMY_SECRET }}
        run: echo "::notice ::Finished doing stuff on main repo"
