# Change to workflow.
name: non-fork
on:
  push:
  pull_request:

jobs:
  non-fork-job:
    if: ${{ !github.event.repository.fork }}
    runs-on: ubuntu-latest
    steps:
      - name: Add a notice on main
        run: echo "::notice ::Build running in main repo"

  post-non-fork-job:
    needs: [non-fork-job]
    if: ${{ !github.event.repository.fork && always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Add a notice on post-non-fork
        run: echo "::notice ::Finished doing stuff on main repo"
