# Change to workflow..
name: post-gradle
on:
  workflow_run:
    workflows: ["main"]
    types: [completed]

jobs:
  report-jobs:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ toJSON(github.event) }}"