name: reusing_workflow

on:
  workflow_dispatch:

env:
  ENV_VAR: This is the env var

jobs:
  reusing_workflow_job:
    uses: ./.github/workflows/reusable-workflow.yml
    secrets:
      SECRET_VAR: ${{ secrets.SECRET_VAR }}
  reusing_action_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Test the reusable action"
        uses: ./.github/actions/test-config-action
