name: run-gradle-build
on: 
  workflow_call:
    inputs:
      gradle-arguments:
        required: true
        type: string
    secrets:
      GRADLE_ENTERPRISE_ACCESS_KEY:
        required: false

env:
  GRADLE_ENTERPRISE_INJECTION_ENABLED: ${{ vars.GRADLE_ENTERPRISE_INJECTION_ENABLED }}
  GRADLE_ENTERPRISE_INJECTION_SERVER_URL: ${{ vars.GRADLE_ENTERPRISE_INJECTION_SERVER_URL }}
  GRADLE_ENTERPRISE_INJECTION_GE_PLUGIN_VERSION: ${{ vars.GRADLE_ENTERPRISE_INJECTION_GE_PLUGIN_VERSION }}
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}

jobs:
  run-gradle-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gradle/gradle-build-action@main
    - run: ./gradlew ${{ inputs.config-path }}
