name: toolchain-test
on:
  workflow_dispatch:

jobs:
  print-toolchains:
    strategy:
      matrix:
        os: [ubuntu-latest]
        gradle-version: [8.3]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: ${{ matrix.gradle-version }}
        build-root-directory: gradle-project
        arguments: -q javaToolchains
    
