name: toolchain-test
on:
  workflow_dispatch:

jobs:
  print-toolchains:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        gradle-version: [7.6.2, 8.0.1, 8.3]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java 29
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '20'
    - name: Setup Java 16
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '16'
    - name: Setup gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: ${{ matrix.gradle-version }}
        cache-disabled: true
    - name: Print toolchains
      shell: bash
      working-directory: gradle-project
      run: | 
        gradle -Porg.gradle.java.installations.auto-download=false -Porg.gradle.java.installations.fromEnv=JAVA_HOME_8_X64,JAVA_HOME_11_X64,JAVA_HOME_17_X64 -q javaToolchains | tee output.txt
        grep -q 'Eclipse Temurin JDK 1.8' output.txt || (echo "::error::Did not detect preinstalled JDK 1.8" && exit 1)
        grep -q 'Eclipse Temurin JDK 11' output.txt || (echo "::error::Did not detect preinstalled JDK 11" && exit 1)
        grep -q 'Eclipse Temurin JDK 17' output.txt || (echo "::error::Did not detect preinstalled JDK 17" && exit 1)
        grep -q 'Eclipse Temurin JDK 16' output.txt || (echo "::error::Did not detect setup-java installed JDK 16" && exit 1)
        grep -q 'Eclipse Temurin JDK 20' output.txt || (echo "::error::Did not detect setup-java installed JDK 20" && exit 1)
        grep -q 'Eclipse Temurin JDK 19' output.txt || (echo "::error::Did not detect JDK 19" && exit 1)
        
    - name: Print Maven config
      shell: bash
      run: |
        cat ~/.m2/settings.xml
        cat ~/.m2/toolchains.xml
