name: toolchain-test
on:
  workflow_dispatch:

jobs:
  print-toolchains:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        gradle-version: [7.6.2, 8.0.1, 8.3]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java 29
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '20'
    - name: Setup Java 16
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '16'
    - name: Setup gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: ${{ matrix.gradle-version }}
        cache-disabled: true
    - name: Print toolchains
      shell: bash
      working-directory: gradle-project
      run: gradle -Porg.gradle.java.installations.auto-download=false -Porg.gradle.java.installations.fromEnv=JAVA_HOME_8_X64,JAVA_HOME_11_X64,JAVA_HOME_17_X64 -q javaToolchains
    - name: Print Maven config
      shell: bash
      run: |
        cat ~/.m2/settings.xml
        cat ~/.m2/toolchains.xml
