name: verify-secret-access

on:
  workflow_dispatch:

jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: print secrets
      run: |
        echo "secrets.REPO_SECRET = ${{ secrets.REPO_SECRET }}"
        echo "contains(secrets.REPO_SECRET, 'foo') = ${{ contains(secrets.REPO_SECRET, 'foo') }}"
    - name: print vars
      run: |
        echo "vars.REPO_VAR = ${{ vars.REPO_VAR }}"
