name: workflow-test
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Do the cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
             ~/.gradle/wrapper
          key: the-cache-${{github.sha}}
      - name: Run Gradle
        run: ./gradlew build
        working-directory: gradle-project

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Do the cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
             ~/.gradle/wrapper
          key: the-cache-${{github.sha}}
      - name: Run Gradle
        run: ./gradlew build
        working-directory: gradle-project

