name: workflow-test
on:
  workflow_dispatch:
jobs:
  work:
    runs-on: [ubuntu-latest, macos-latest]
    strategy:
      matrix:
        java: [ 11, 12, 13 ]
        gradle: [5, 6, 7]
        other: [a, b, c]
    steps:
    - name: Print Job
      run: echo "The job is running"
