name: workflow-test
on:
  workflow_dispatch:
jobs:
  work:
    strategy:
      matrix:
        java: [ 11, 12, 13 ]
        gradle: [5, 6, 7]
        other: [a, b, c]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Print Job
      run: echo "The job is running"
